drop table comment;
drop table photos;
drop table place;
drop table users;
DROP SEQUENCE comment_id_seq;
drop sequence photos_id_seq;
drop sequence place_id_seq;
drop sequence users_id_seq;
drop table cities;