Progracqteur\WikipedaleBundle\Entity\Model\Place:
  getters:
    creator: 
      - NotNull: {message: La creator ne peut être nul}
      - Valid: ~
  properties:
    description:
      - MaxLength: {limit: 1000, message: La description ne peut pas être plus longue que 1000 caractères}
    geom:
      - NotNull: {message: Indiquez un emplacement géographique}
    moderatorComment:
      - MaxLength: {limit: 1000, message: Le commentaire du modérateur ne peut pas être plus long que 1000 caractères}
  constraints:
    - Callback:
        methods: [isStatusesValid, hasOnlyOneChange, isCategoriesValid, isManagerValid]

Progracqteur\WikipedaleBundle\Entity\Model\Photo:
  getters:
    fileObject:
      - Image:
          maxSize: 5000k
          maxSizeMessage: Le fichier est trop volumineux. Réduisez-le avant envoi.
          mimeTypes: [image/jpeg]
          mimeTypesMessage: Le fichier n'est pas un format accepté. Seul le format jpg est accepté.
    creator:
      - NotNull: {message: Le créateur ne peut pas être null}
    place:
      - NotNull: {message: La photo doit être reliée à un emplacement}
  properties:
    legend:
      - MaxLength: {limit: 500, message: La légende ne peut dépasser 500 caractères }
      
Progracqteur\WikipedaleBundle\Entity\Management\Notation:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: id
        message: admin.notation.id.not.unique
  properties:
    id: 
      - Regex:
          pattern: "/^[a-z0-9]/"
          message: admin.notation.id.must_be_character_alphabeticals_or_numeric
      - MaxLength: 20
      - MinLength: 3
    name:
      - NotBlank: ~
      - MaxLength: 60
      - MinLength: 3

Progracqteur\WikipedaleBundle\Entity\Management\Group:
  properties:
    name:
      - NotBlank: ~
      - MinLength: 5
      - MaxLength: 120
  constraints:
    - Callback:
        methods: [isValidType, isValidNotation]
      
Progracqteur\WikipedaleBundle\Entity\Management\UnregisteredUser:
  properties:
    ip: 
      - Ip:
          version: all
      - NotBlank: {message: user.ip.not_blank}
      - NotNull: {message: user.ip.not_null}
    label:
      - NotNull: {message: user.validation.label.not_null}
      - NotBlank: {message: user.validation.label.not_blank}
      - MinLength:
          limit: 3
          message: user.validation.label.more_than_three_letters
      - MaxLength:
          limit: 50
          message: user.validation.label.maximum_50_letters
    email:
      - NotNull: {message: user.validation.email.not_null}
      - NotBlank: {message: user.validation.email.not_blank}
      - Email: 
          message: user.validation.email.not_valid_or_domain_not_exist
          #checkMX: true
    phonenumber:
      - NotNull: {message: user.validation.phonenumber.not_null}
      
Progracqteur\WikipedaleBundle\Entity\Model\Category:
  constraints:
    - Callback:
        methods: [isParentAChild]
  getters:
    label:
      - NotBlank: ~
      - MinLength: {limit: 3, message: admin.category.form.label.min_length}
      - MaxLength: {limit: 240, message: admin.category.form.label.max_length}
      
      
Progracqteur\WikipedaleBundle\Entity\Model\Comment:
  getters:
    type: 
      - NotNull: 
          message: validation.comment.type.not_null
    content:
      - MinLength: {limit: 2, message: validation.comment.message.min_length}
      - MaxLength: {limit: 5000, message: validation.comment.message.max_length}
    place:
      - NotNull: 
          message: validation.comment.place.not_null
    creator:
      - NotNull:
          message: validation.comment.creator.not_null
          
      