Progracqteur\WikipedaleBundle\Entity\Management\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    creationDate: 
      type: datetime
    infos: 
      type: hash
    nbComment: 
      type: integer
    nbVote: 
      type: integer
    phonenumber:
      type: string
      length: 50
    label:
      type: string
      length: 150
      column: fullLabel
    virtual:
      type: boolean
      default: false
  manyToMany:
    groups:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\Group
      nullable: true
  oneToMany:
    notificationSubscriptions:
      targetEntity: Progracqteur\WikipedaleBundle\Entity\Management\NotificationSubscription
      mappedBy: owner
      cascade: [persist, refresh, remove]